### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'axis')

### ISSUE THREAD

**Issue by LKing12** [SauravKanchan/svelte-chartjs#72]
Not happening with `npm run autobuild` but is with `npm run build`  when I deploy my code, I'm getting this
![image](https://user-images.githubusercontent.com/37575563/188553321-aa3bb1ac-3aec-471a-8299-287e8e62127d.png)
And the chart isn't rendering
For a dataset that looks like this 
![image](https://user-images.githubusercontent.com/37575563/188553486-76e78d7a-65ab-49ff-87d9-d96f63de17a1.png)
And a svelte config like

```
<script>
import { onMount } from 'svelte';
import {  fetchGet } from "../../helpers";
import { Bar } from 'svelte-chartjs';
import {
    Chart,
    Title,
    Tooltip,
    Legend,
    BarElement,
    CategoryScale,
    LinearScale,
  } from 'chart.js';

  Chart.register(
    Title,
    Tooltip,
    BarElement,
    CategoryScale,
    LinearScale
  );
let loaded = false;
let data = {
  labels: [],
};

onMount(async () => {
    let res = await fetchGet('/api/pool/all/stats');
    data = await res.data;
    data = data;
    loaded = true;
 });
</script>
<div>
<div>
    {#if loaded}
    <Bar {data} options={{ responsive: true  }}/>    
    {/if}
</div>
```

**Comment by LKing12** [comment]
So it took two steps:
1. delete the rollup uglify plugin 
2. Add scales in the options
```
    {#if loaded}
    <Bar {data} options={{ responsive: true,legend: {
        display: true, position:'top'
      },
      scales: {
        x: {
          type: 'category'
        },
        y: {
          type: 'linear',
          labels:['website text', 'imgae text', 'document text']

        }
      } }}
```

But now it's rendering two y-axis ?
![image](https://user-images.githubusercontent.com/37575563/188567660-818d245e-fd5c-4f73-b941-e6ae8ea06e18.png)

**Comment by dangreen** [comment]
@LKing12 Hi. Could you please fork [this sandbox](https://codesandbox.io/s/github/SauravKanchan/svelte-chartjs/tree/master/sandboxes/bar) and reproduce the issue?

**Comment by Zedespook** [comment]
> @LKing12 Hi. Could you please fork [this sandbox](https://codesandbox.io/s/github/SauravKanchan/svelte-chartjs/tree/master/sandboxes/bar) and reproduce the issue?

Same issue, we are developing the same app (using Rollup). I have sandboxed the snippet within the app. These are the results:

Using `npm run build`
![image](https://user-images.githubusercontent.com/26501287/191732169-4f882192-34b6-44bb-8319-320814d805d1.png)

Using `npm run autobuild`
![image](https://user-images.githubusercontent.com/26501287/191732359-2e8cff84-8868-4dc8-8bcc-9b35b85e526e.png)

**Comment by dangreen** [comment]
@Zedespook @LKing12 What version of svelte-chartjs are you using?

**Comment by Zedespook** [comment]
In our `package.json` we specified `"svelte-chartjs": "^2.1.1"`.

**Comment by dangreen** [comment]
@Zedespook Please try v3

**Comment by Zedespook** [comment]
Installed `svelte-chartjs 3.0.1`. Unfortunately, this provides the same results.

**Comment by dangreen** [comment]
@Zedespook Could you please provide minimal repo with reproduction?

**Comment by Zedespook** [comment]
> @Zedespook Could you please provide minimal repo with reproduction?

Here you go, I made [this sandbox](https://codesandbox.io/s/jovial-violet-0yv8d1?file=/src/App.svelte). In the sandbox itself, nothing will show. You will have to download it, and you can re-create the issue by the following steps:

1. *Terminal 1*: `npm install`
2. *Terminal 1*: `npm run build`
3. Open another terminal to serve the page
4. *Terminal 2*: `cd public`
5. *Terminal 2*: `npx serve` (install it, or use your favorite server)
6. Open `localhost:5000` (or whatever port you use)
7. There is no chart

Now when we talked about the `npm run autobuild` having the chart fully functional, I can show you what we mean:

1. Go back to *Terminal 1*
2. `npm run autobuild`
3. Open/refresh `localhost:5000`
4. The chart should appear

The problem here is that if we would like to use this in production, we would have to deal with this bug, and `autobuild` is just not ideal in production.

Let me know if you figured something out.

**Comment by dangreen** [comment]
@Zedespook 

```js
      terser({
        // mangle: { properties: { regex: /^_/ } },
        output: { comments: false }
      })
```

it is unsafe to mangle properties, so just disable this option and all will work perfectly

**Comment by Zedespook** [comment]
That indeed works on `build` thanks!
